const routes = require('next-routes')

module.exports = routes()
  .add('phrases', '/phrases')
  .add('poems', '/poems')
  .add('poem', '/poems/:id')
  .add('phrase', '/poems/:id/phrase/:phraseId', 'poem')
  .add('authors', '/authors')
  .add('author', '/authors/:id')
  .add('register', '/register', 'login')
  .add('login', '/login', 'login')
  .add('profile', '/users/:userId/:tag')